version: '3.7'

services:
  pm_wordpress:
    image: wordpress:latest
    volumes:
      - wordpress:/var/www/html:rw
      - ./plugin:/var/www/html/wp-content/plugins/plebeian_market:ro
    ports:
      - 8000:80
    restart: always
    environment:
      - WORDPRESS_DB_HOST=pm_wordpress_db
      - WORDPRESS_DB_USER=wordpress
      - WORDPRESS_DB_PASSWORD=wordpress
      - WORDPRESS_DB_NAME=wordpress
    depends_on:
      - pm_wordpress_db

  pm_wordpress_db:
    image: mariadb
    command: '--default-authentication-plugin=mysql_native_password'
    volumes:
      - plebeian_market_wordpress_plugin_db_data:/var/lib/mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=pass4root
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=wordpress
      - MYSQL_PASSWORD=wordpress
    expose:
      - 3306
      - 33060

  pb_wordpress_db_phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - MYSQL_USERNAME=root
      - MYSQL_ROOT_PASSWORD=pass4root
      - PMA_HOST=pm_wordpress_db
    depends_on:
      - pm_wordpress_db

  pm_wordpress_cli:
    image: wordpress:cli
    command: tail -f /dev/null
    volumes:
      - wordpress:/var/www/html:rw
      - ./plugin:/var/www/html/wp-content/plugins/plebeian_market:ro
      - ./assets:/var/www/html/assets:ro
    environment:
      - WORDPRESS_DB_HOST=pm_wordpress_db
      - WORDPRESS_DB_USER=wordpress
      - WORDPRESS_DB_PASSWORD=wordpress
      - WORDPRESS_DB_NAME=wordpress
    depends_on:
      - pm_wordpress
      - pm_wordpress_db
    user: "33:33"

volumes:
  plebeian_market_wordpress_plugin_db_data:
  wordpress:

networks:
  default:
    name: plebeian-market_db_network
    external: true